# Generated by Django 5.1.2 on 2025-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AC', 'Acontecendo'), ('SL', 'Saque Liberado')], max_length=2)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('investimento', models.CharField(choices=[('FREE', 'Free'), ('OPCIONAL', 'Opção de Investimento'), ('PAGO', 'Pago')], max_length=10)),
                ('valor_investimento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
