# Generated by Django 5.1.2 on 2025-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0002_airdrop_data_publicacao_airdrop_plataforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
